server:
  port: 5002

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://61.172.179.56:3306/crm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
          username: root
          password: aTze0ubeJisUbDKB
          type: com.zaxxer.hikari.HikariDataSource
  cache:
    type: redis  # 可选 redis、none、ehcache
  redis:
    host: 61.172.179.56
    password: aTze0ubeJisUbDKB
    port: 6379
    database: 0
  cloud:
    # Spring Cloud Stream 配置项，对应 BindingServiceProperties 类
    stream:
      enabled: true # action log 记录方式是否启用消息队列
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          name-server: 61.172.179.56:9876 # RocketMQ Namesrv 地址
          group: DCODE_GROUP


jwtUtils:
  id: jwt
  secret: 6686df7fc3a34e26a61c034d5ec82488
  ttlMillis: 3600000

#启信宝
qixin:
  appkey: 266b9724-e6df-4897-ab08-a00d9554c2fd
  secretKey: a1177eb8-126b-403c-acbd-026ff9eceb5d
  host: https://api.qixin.com/
  profile: APIService

#企业微信
weChat:
  corpid: ww21ecf19d6c519f83
  corpsecret: G3rf94sZqkZJ90duduA-TCIaou-QUeA9qNe7ANtjR9Y
  agentid: 1000006


#百度短信
baidu:
  sms:
    accessKey: 9aa348551a8d40dc8077d619c6120772
    secretAccess: 61ce9306d76a41868d1193536fda7653
    endpoint: http://smsv3.bj.baidubce.com
    signature:
      #短信签名的id(百度云获取)
      id: sms-sign-WmvZrj56673
    template:
      #短信模板：短信验证码模板code
      code: sms-tmpl-SDDBTY24370
      #短信模板：消息模板code
      msg: sms-tmpl-snvDbF24911

nacos:
  namespace: 7f6a420d-1056-48de-9f85-8e9f9549fe8b
  config-group: DEV_GROUP
  discovery-group: SEATA_GROUP
  server-addr: 61.172.179.56:8848
  username: nacos
  password: nacos